# Generated by Django 4.2.25 on 2025-11-03 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='assigned_phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^1\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^1\\d{10}$')]),
        ),
    ]
