# Generated by Django 4.2.25 on 2025-11-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invitationcode_assigned_phone_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=64, unique=True)),
                ('ip', models.CharField(max_length=64)),
                ('gpu_total', models.IntegerField(default=0)),
                ('gpu_free', models.IntegerField(default=0)),
                ('gpu_busy', models.IntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=16)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('auth_token', models.CharField(max_length=64, unique=True)),
                ('api_port', models.IntegerField(default=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['node_name'],
            },
        ),
        migrations.AddField(
            model_name='traintask',
            name='assigned_gpus',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='traintask',
            name='assigned_node',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='traintask',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traintask',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traintask',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
