# Generated by Django 4.2.27 on 2026-01-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_create_django_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitationCode',
        ),
    ]
