# Generated by Django 4.2.27 on 2026-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_delete_invitationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="traintask",
            name="checkpoint_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="assigned_gpus",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="assigned_node",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="checkpoint_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="server_host",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="server_port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencetask",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
