# Generated by Django 4.2.27 on 2026-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_session'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['token_hash'], name='api_userses_token_h_226657_idx'),
        ),
    ]
